services:

  web-init:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./web:/app
    command: npm install

  web:
    extends:
      service: web-init
    environment:
      - PORT=${WEB_PORT:-3000}
    env_file:
      - .env
    command: npm run dev -- --port ${WEB_PORT:-3000}
    ports:
      - "${WEB_PORT:-3000}:${WEB_PORT:-3000}"
    depends_on:
      web-init:
        condition: service_completed_successfully
    networks:
      - strapi

networks:
  strapi:
    driver: bridge
