// Generated by code/scripts/sync-static-catalog.mjs. Do not edit by hand.
export default {
  "collections": [
    {
      "name": "Oriental",
      "slug": "oriental",
      "description": "Collection: Oriental",
      "publishedAt": "2025-07-16T22:19:42.286Z",
      "locale": "en"
    },
    {
      "name": "B&W",
      "slug": "black-and-white",
      "description": "Collection: B&W",
      "publishedAt": "2025-07-20T15:08:03.709Z",
      "locale": "en"
    },
    {
      "name": "Botánica",
      "slug": "botanica",
      "description": "Collection: Botánica",
      "publishedAt": "2025-07-20T15:19:29.053Z",
      "locale": "en"
    },
    {
      "name": "Dorada",
      "slug": "dorada",
      "description": "Collection: Dorada",
      "publishedAt": "2025-07-20T15:19:55.164Z",
      "locale": "en"
    },
    {
      "name": "2025",
      "slug": "2025",
      "description": "Collection: 2025",
      "publishedAt": "2025-07-22T23:49:30.226Z",
      "locale": "en"
    },
    {
      "name": "2024",
      "slug": "2024",
      "description": "Collection: 2024",
      "publishedAt": "2025-07-23T03:49:24.481Z",
      "locale": "en"
    }
  ],
  "artworks": [
    {
      "title": "Soleil et Montagnes",
      "slug": "soleil-et-montagnes",
      "description": "Acrylic, canvas paper\n13\"x16\"",
      "artist": "EONMUN",
      "year": 2025,
      "publishedAt": "2025-07-23T03:56:51.040Z",
      "locale": "en",
      "images": [
        {
          "url": "https://r2.eonmun.com/soleil_et_montagnes_what_s_inside_a_black_hole_jpg_14c4a50009.jpeg",
          "isDefault": true,
          "caption": "Soleil et Montagnes"
        }
      ],
      "defaultImageUrl": "https://r2.eonmun.com/soleil_et_montagnes_what_s_inside_a_black_hole_jpg_14c4a50009.jpeg",
      "collections": [
        {
          "name": "Oriental",
          "slug": "oriental",
          "description": "Collection: Oriental",
          "publishedAt": "2025-07-16T22:19:42.286Z",
          "locale": "en"
        }
      ]
    },
    {
      "title": "Quiescent Citadel",
      "slug": "quiescent-citadel",
      "description": "Watercolor, paper\n12\"x16\"",
      "artist": "EONMUN",
      "year": 2025,
      "publishedAt": "2025-07-23T03:56:56.621Z",
      "locale": "en",
      "images": [
        {
          "url": "https://r2.eonmun.com/quiescent_citadel_41dd0dd7f0.jpeg",
          "isDefault": true,
          "caption": "Quiescent Citadel"
        },
        {
          "url": "https://r2.eonmun.com/quiescent_citadel_42bd592172.jpeg",
          "isDefault": false,
          "caption": "Quiescent Citadel"
        }
      ],
      "defaultImageUrl": "https://r2.eonmun.com/quiescent_citadel_41dd0dd7f0.jpeg",
      "collections": [
        {
          "name": "B&W",
          "slug": "black-and-white",
          "description": "Collection: B&W",
          "publishedAt": "2025-07-20T15:08:03.709Z",
          "locale": "en"
        }
      ]
    },
    {
      "title": "Persimmons del Oro",
      "slug": "persimmons-del-oro",
      "description": "Watercolor, pencil, gold leaf, paper\n14\"x18\"",
      "artist": "EONMUN",
      "year": 2025,
      "publishedAt": "2025-07-23T03:57:11.617Z",
      "locale": "en",
      "images": [
        {
          "url": "https://r2.eonmun.com/PERS_Int_b08c7cef7c.jpeg",
          "isDefault": true,
          "caption": "Persimmons del Oro"
        }
      ],
      "defaultImageUrl": "https://r2.eonmun.com/PERS_Int_b08c7cef7c.jpeg",
      "collections": [
        {
          "name": "Dorada",
          "slug": "dorada",
          "description": "Collection: Dorada",
          "publishedAt": "2025-07-20T15:19:55.164Z",
          "locale": "en"
        }
      ]
    },
    {
      "title": "Limones del Cobre",
      "slug": "limones-del-cobre",
      "description": null,
      "artist": "EONMUN",
      "year": null,
      "publishedAt": "2025-07-23T03:57:29.040Z",
      "locale": "en",
      "images": [
        {
          "url": "https://r2.eonmun.com/LIM_Int_2b192a6609.jpeg",
          "isDefault": true,
          "caption": "Limones del Cobre"
        }
      ],
      "defaultImageUrl": "https://r2.eonmun.com/LIM_Int_2b192a6609.jpeg",
      "collections": [
        {
          "name": "Dorada",
          "slug": "dorada",
          "description": "Collection: Dorada",
          "publishedAt": "2025-07-20T15:19:55.164Z",
          "locale": "en"
        }
      ]
    },
    {
      "title": "Casa de Fuji",
      "slug": "casa-de-fuji",
      "description": "Acrylic, watercolor, paper\n12\"x14\"",
      "artist": "EONMUN",
      "year": 2024,
      "publishedAt": "2025-07-23T03:59:52.922Z",
      "locale": "en",
      "images": [
        {
          "url": "https://r2.eonmun.com/Casa_De_Fuji_Int_0b8604171b.jpeg",
          "isDefault": true,
          "caption": "Casa de Fuji"
        }
      ],
      "defaultImageUrl": "https://r2.eonmun.com/Casa_De_Fuji_Int_0b8604171b.jpeg",
      "collections": [
        {
          "name": "Oriental",
          "slug": "oriental",
          "description": "Collection: Oriental",
          "publishedAt": "2025-07-16T22:19:42.286Z",
          "locale": "en"
        }
      ]
    },
    {
      "title": "Banc de Poissons",
      "slug": "banc-de-poissons",
      "description": "Watercolor, rice paper\n12\"x14\"",
      "artist": "EONMUN",
      "year": 2024,
      "publishedAt": "2025-07-23T04:13:52.427Z",
      "locale": "en",
      "images": [
        {
          "url": "https://r2.eonmun.com/Banc_De_Poison_Int_0bbb21ceb8.jpeg",
          "isDefault": true,
          "caption": "Banc de Poissons"
        }
      ],
      "defaultImageUrl": "https://r2.eonmun.com/Banc_De_Poison_Int_0bbb21ceb8.jpeg",
      "collections": [
        {
          "name": "2024",
          "slug": "2024",
          "description": "Collection: 2024",
          "publishedAt": "2025-07-23T03:49:24.481Z",
          "locale": "en"
        }
      ]
    },
    {
      "title": "Occullilium",
      "slug": "occullilium",
      "description": "Watercolor, pencil, gold leaf, paper\n14\"x18\"",
      "artist": "EONMUN",
      "year": 2025,
      "publishedAt": "2025-07-23T04:15:02.521Z",
      "locale": "en",
      "images": [
        {
          "url": "https://r2.eonmun.com/LIL_Int_d455e0684a.jpeg",
          "isDefault": true,
          "caption": "Occullilium"
        }
      ],
      "defaultImageUrl": "https://r2.eonmun.com/LIL_Int_d455e0684a.jpeg",
      "collections": [
        {
          "name": "Botánica",
          "slug": "botanica",
          "description": "Collection: Botánica",
          "publishedAt": "2025-07-20T15:19:29.053Z",
          "locale": "en"
        }
      ]
    },
    {
      "title": "Equestrian Equilibrium",
      "slug": "equestrian-equilibrium",
      "description": "Watercolor, gold leaf, paper\n13\"x16\"",
      "artist": "EONMUN",
      "year": 2025,
      "publishedAt": "2025-07-23T03:52:49.216Z",
      "locale": "en",
      "images": [
        {
          "url": "https://r2.eonmun.com/eehor_d23eb41f2c.jpg",
          "isDefault": true,
          "caption": "Equestrian Equilibrium"
        }
      ],
      "defaultImageUrl": "https://r2.eonmun.com/eehor_d23eb41f2c.jpg",
      "collections": [
        {
          "name": "2025",
          "slug": "2025",
          "description": "Collection: 2025",
          "publishedAt": "2025-07-22T23:49:30.226Z",
          "locale": "en"
        }
      ]
    },
    {
      "title": "Quetzalcōātlin tetl",
      "slug": "quetzalcoatlin-tetl",
      "description": "Watercolor, pencil, paper\n14\"x18\"",
      "artist": "EONMUN",
      "year": 2025,
      "publishedAt": "2025-07-23T03:53:18.518Z",
      "locale": "en",
      "images": [
        {
          "url": "https://r2.eonmun.com/quetzalcoatlin_tetl_e3a31b4836.jpeg",
          "isDefault": true,
          "caption": "Quetzalcōātlin tetl"
        }
      ],
      "defaultImageUrl": "https://r2.eonmun.com/quetzalcoatlin_tetl_e3a31b4836.jpeg",
      "collections": [
        {
          "name": "B&W",
          "slug": "black-and-white",
          "description": "Collection: B&W",
          "publishedAt": "2025-07-20T15:08:03.709Z",
          "locale": "en"
        }
      ]
    },
    {
      "title": "Camélia",
      "slug": "camelia",
      "description": "Japanese ink, rice paper\n19\"x25\"",
      "artist": "EONMUN",
      "year": 2024,
      "publishedAt": "2025-07-23T04:19:07.320Z",
      "locale": "en",
      "images": [
        {
          "url": "https://r2.eonmun.com/Camelia_b90020b2bc.jpeg",
          "isDefault": true,
          "caption": "Camélia"
        }
      ],
      "defaultImageUrl": "https://r2.eonmun.com/Camelia_b90020b2bc.jpeg",
      "collections": [
        {
          "name": "Botánica",
          "slug": "botanica",
          "description": "Collection: Botánica",
          "publishedAt": "2025-07-20T15:19:29.053Z",
          "locale": "en"
        }
      ]
    }
  ],
  "products": [
    {
      "type": "artwork",
      "artworkSlug": "soleil-et-montagnes",
      "name": "Soleil et Montagnes",
      "slug": "soleil-et-montagnes",
      "description": "Original watercolor artwork with certificate of authenticity",
      "imageUrl": "https://r2.eonmun.com/soleil_et_montagnes_what_s_inside_a_black_hole_jpg_14c4a50009.jpeg",
      "price": 100000,
      "quantity": null
    },
    {
      "type": "artwork",
      "artworkSlug": "quiescent-citadel",
      "name": "Quiescent Citadel",
      "slug": "quiescent-citadel",
      "description": "Original watercolor artwork with certificate of authenticity",
      "imageUrl": "https://r2.eonmun.com/quiescent_citadel_41dd0dd7f0.jpeg",
      "price": 120000,
      "quantity": null
    },
    {
      "type": "artwork",
      "artworkSlug": "persimmons-del-oro",
      "name": "Persimmons del Oro",
      "slug": "persimmons-del-oro",
      "description": "Original watercolor artwork with gold leaf and certificate of authenticity",
      "imageUrl": "https://r2.eonmun.com/PERS_Int_b08c7cef7c.jpeg",
      "price": 150000,
      "quantity": null
    },
    {
      "type": "artwork",
      "artworkSlug": "limones-del-cobre",
      "name": "Limones del Cobre",
      "slug": "limones-del-cobre",
      "description": "Original artwork with certificate of authenticity",
      "imageUrl": "https://r2.eonmun.com/LIM_Int_2b192a6609.jpeg",
      "price": 140000,
      "quantity": null
    },
    {
      "type": "artwork",
      "artworkSlug": "casa-de-fuji",
      "name": "Casa de Fuji",
      "slug": "casa-de-fuji",
      "description": "Original mixed media artwork with certificate of authenticity",
      "imageUrl": "https://r2.eonmun.com/Casa_De_Fuji_Int_0b8604171b.jpeg",
      "price": 110000,
      "quantity": null
    },
    {
      "type": "artwork",
      "artworkSlug": "banc-de-poissons",
      "name": "Banc de Poissons",
      "slug": "banc-de-poissons",
      "description": "Original watercolor on rice paper with certificate of authenticity",
      "imageUrl": "https://r2.eonmun.com/Banc_De_Poison_Int_0bbb21ceb8.jpeg",
      "price": 95000,
      "quantity": null
    },
    {
      "type": "artwork",
      "artworkSlug": "occullilium",
      "name": "Occullilium",
      "slug": "occullilium",
      "description": "Original watercolor artwork with gold leaf and certificate of authenticity",
      "imageUrl": "https://r2.eonmun.com/LIL_Int_d455e0684a.jpeg",
      "price": 160000,
      "quantity": null
    },
    {
      "type": "artwork",
      "artworkSlug": "equestrian-equilibrium",
      "name": "Equestrian Equilibrium",
      "slug": "equestrian-equilibrium",
      "description": "Original watercolor artwork with gold leaf and certificate of authenticity",
      "imageUrl": "https://r2.eonmun.com/eehor_d23eb41f2c.jpg",
      "price": 130000,
      "quantity": null
    },
    {
      "type": "artwork",
      "artworkSlug": "quetzalcoatlin-tetl",
      "name": "Quetzalcōātlin tetl",
      "slug": "quetzalcoatlin-tetl",
      "description": "Original watercolor artwork with certificate of authenticity",
      "imageUrl": "https://r2.eonmun.com/quetzalcoatlin_tetl_e3a31b4836.jpeg",
      "price": 145000,
      "quantity": null
    },
    {
      "type": "artwork",
      "artworkSlug": "camelia",
      "name": "Camélia",
      "slug": "camelia",
      "description": "Original Japanese ink artwork on rice paper with certificate of authenticity",
      "imageUrl": "https://r2.eonmun.com/Camelia_b90020b2bc.jpeg",
      "price": 125000,
      "quantity": null
    }
  ],
  "homepage": [
    {
      "title": "Persimmons del Oro",
      "slug": "persimmons-del-oro",
      "description": "Watercolor, pencil, gold leaf, paper\n14\"x18\"",
      "artist": "EONMUN",
      "year": 2025,
      "publishedAt": "2025-07-23T03:57:11.617Z",
      "locale": "en",
      "images": [
        {
          "url": "https://r2.eonmun.com/PERS_Int_b08c7cef7c.jpeg",
          "isDefault": true,
          "caption": "Persimmons del Oro"
        }
      ],
      "defaultImageUrl": "https://r2.eonmun.com/PERS_Int_b08c7cef7c.jpeg",
      "collections": [
        {
          "name": "Dorada",
          "slug": "dorada",
          "description": "Collection: Dorada",
          "publishedAt": "2025-07-20T15:19:55.164Z",
          "locale": "en"
        }
      ]
    },
    {
      "title": "Casa de Fuji",
      "slug": "casa-de-fuji",
      "description": "Acrylic, watercolor, paper\n12\"x14\"",
      "artist": "EONMUN",
      "year": 2024,
      "publishedAt": "2025-07-23T03:59:52.922Z",
      "locale": "en",
      "images": [
        {
          "url": "https://r2.eonmun.com/Casa_De_Fuji_Int_0b8604171b.jpeg",
          "isDefault": true,
          "caption": "Casa de Fuji"
        }
      ],
      "defaultImageUrl": "https://r2.eonmun.com/Casa_De_Fuji_Int_0b8604171b.jpeg",
      "collections": [
        {
          "name": "Oriental",
          "slug": "oriental",
          "description": "Collection: Oriental",
          "publishedAt": "2025-07-16T22:19:42.286Z",
          "locale": "en"
        }
      ]
    },
    {
      "title": "Banc de Poissons",
      "slug": "banc-de-poissons",
      "description": "Watercolor, rice paper\n12\"x14\"",
      "artist": "EONMUN",
      "year": 2024,
      "publishedAt": "2025-07-23T04:13:52.427Z",
      "locale": "en",
      "images": [
        {
          "url": "https://r2.eonmun.com/Banc_De_Poison_Int_0bbb21ceb8.jpeg",
          "isDefault": true,
          "caption": "Banc de Poissons"
        }
      ],
      "defaultImageUrl": "https://r2.eonmun.com/Banc_De_Poison_Int_0bbb21ceb8.jpeg",
      "collections": [
        {
          "name": "2024",
          "slug": "2024",
          "description": "Collection: 2024",
          "publishedAt": "2025-07-23T03:49:24.481Z",
          "locale": "en"
        }
      ]
    },
    {
      "title": "Soleil et Montagnes",
      "slug": "soleil-et-montagnes",
      "description": "Acrylic, canvas paper\n13\"x16\"",
      "artist": "EONMUN",
      "year": 2025,
      "publishedAt": "2025-07-23T03:56:51.040Z",
      "locale": "en",
      "images": [
        {
          "url": "https://r2.eonmun.com/soleil_et_montagnes_what_s_inside_a_black_hole_jpg_14c4a50009.jpeg",
          "isDefault": true,
          "caption": "Soleil et Montagnes"
        }
      ],
      "defaultImageUrl": "https://r2.eonmun.com/soleil_et_montagnes_what_s_inside_a_black_hole_jpg_14c4a50009.jpeg",
      "collections": [
        {
          "name": "Oriental",
          "slug": "oriental",
          "description": "Collection: Oriental",
          "publishedAt": "2025-07-16T22:19:42.286Z",
          "locale": "en"
        }
      ]
    }
  ]
};
