import type { Metadata } from "next";
import { Abel   } from "next/font/google";
import "./globals.css";
import { Layout } from "@/components/Layout/Layout";
import { headers } from "next/headers";
import { Providers } from "@/context";

const abel = Abel ({
  variable: "--font-abel",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers()
  const cookies = headersList.get('cookie')
  
  return (
    <html lang="en">
      <body
        className={`${abel.className} antialiased`}
      >
        <Providers cookies={cookies}>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
