import type { Metadata } from "next";
import { Abel   } from "next/font/google";
import "./globals.css";
import { Layout } from "@/components/Layout/Layout";
import { headers } from "next/headers";
import { Providers } from "@/context";

const abel = Abel ({
  variable: "--font-abel",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers()
  const cookies = headersList.get('cookie')
  
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const storedColorScheme = localStorage.getItem('color-scheme');
                if (storedColorScheme) {
                  document.documentElement.classList.add(storedColorScheme);
                } else {
                  const systemPreference = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                  document.documentElement.classList.add(systemPreference);
                }
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${abel.className} antialiased`}
      >
        <Providers cookies={cookies}>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
